/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Subscriber } from "./Subscriber";
import { SubscriberCountArgs } from "./SubscriberCountArgs";
import { SubscriberFindManyArgs } from "./SubscriberFindManyArgs";
import { SubscriberFindUniqueArgs } from "./SubscriberFindUniqueArgs";
import { CreateSubscriberArgs } from "./CreateSubscriberArgs";
import { UpdateSubscriberArgs } from "./UpdateSubscriberArgs";
import { DeleteSubscriberArgs } from "./DeleteSubscriberArgs";
import { SubscriptionFindManyArgs } from "../../subscription/base/SubscriptionFindManyArgs";
import { Subscription } from "../../subscription/base/Subscription";
import { SubscriberService } from "../subscriber.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Subscriber)
export class SubscriberResolverBase {
  constructor(
    protected readonly service: SubscriberService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Subscriber",
    action: "read",
    possession: "any",
  })
  async _subscribersMeta(
    @graphql.Args() args: SubscriberCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Subscriber])
  @nestAccessControl.UseRoles({
    resource: "Subscriber",
    action: "read",
    possession: "any",
  })
  async subscribers(
    @graphql.Args() args: SubscriberFindManyArgs
  ): Promise<Subscriber[]> {
    return this.service.subscribers(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Subscriber, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Subscriber",
    action: "read",
    possession: "own",
  })
  async subscriber(
    @graphql.Args() args: SubscriberFindUniqueArgs
  ): Promise<Subscriber | null> {
    const result = await this.service.subscriber(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Subscriber)
  @nestAccessControl.UseRoles({
    resource: "Subscriber",
    action: "create",
    possession: "any",
  })
  async createSubscriber(
    @graphql.Args() args: CreateSubscriberArgs
  ): Promise<Subscriber> {
    return await this.service.createSubscriber({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Subscriber)
  @nestAccessControl.UseRoles({
    resource: "Subscriber",
    action: "update",
    possession: "any",
  })
  async updateSubscriber(
    @graphql.Args() args: UpdateSubscriberArgs
  ): Promise<Subscriber | null> {
    try {
      return await this.service.updateSubscriber({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Subscriber)
  @nestAccessControl.UseRoles({
    resource: "Subscriber",
    action: "delete",
    possession: "any",
  })
  async deleteSubscriber(
    @graphql.Args() args: DeleteSubscriberArgs
  ): Promise<Subscriber | null> {
    try {
      return await this.service.deleteSubscriber(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Subscription], { name: "subscriptions" })
  @nestAccessControl.UseRoles({
    resource: "Subscription",
    action: "read",
    possession: "any",
  })
  async findSubscriptions(
    @graphql.Parent() parent: Subscriber,
    @graphql.Args() args: SubscriptionFindManyArgs
  ): Promise<Subscription[]> {
    const results = await this.service.findSubscriptions(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
